---
- name: Create Resources Folder
  file:
    path: docker-folder
    state: directory

- name: Clone
  git:
    repo: "http://{{ username }}:{{ password }}@gitlab/gitlab/DTS_AdopwithChef/Tomcat.git"
    dest: docker-folder

- name: Download war file
  get_url:
    url: "http://{{ username }}:{{ password }}@nexus:8081/nexus/service/local/repositories/snapshots/content/SnapshotsActivity/CurrencyConverter/1/CurrencyConverter-1.war"
    dest: docker-folder/Resources
    mode: 0644
